#!/bin/bash

# Dropbox OAuth Check Script

echo "======================================"
echo "DROPBOX OAUTH CONFIGURATION CHECK"
echo "======================================"
echo ""

echo "1. Client ID (App key):"
echo "   lkopmthbwccrgen"
echo ""

echo "2. Redirect URI (muss EXAKT so in Console stehen):"
echo "   https://cautious-waddle-wj6rpvv76jw39x5q-3000.app.github.dev/api/oauth/callback/dropbox"
echo ""

echo "3. In der Dropbox Console überprüfen:"
echo "   - Öffne: https://www.dropbox.com/developers/apps"
echo "   - Klicke auf deine App"
echo "   - Prüfe unter 'Settings':"
echo ""
echo "   ✓ App key = lkopmthbwccrgen"
echo "   ✓ App secret = exx1e2mfrhor1yf (sollte übereinstimmen)"
echo ""
echo "   - Prüfe unter 'Settings' → 'OAuth 2' → 'Redirect URIs':"
echo "   ✓ https://cautious-waddle-wj6rpvv76jw39x5q-3000.app.github.dev/api/oauth/callback/dropbox"
echo ""

echo "4. Prüfe den App-Typ:"
echo "   - Unter 'Settings' ganz oben sollte stehen:"
echo "   ✓ 'Scoped access' (NICHT 'Full Dropbox')"
echo ""

echo "5. Prüfe Permissions:"
echo "   - Klicke auf 'Permissions' Tab"
echo "   ✓ files.content.write (checked)"
echo "   ✓ files.content.read (checked)"
echo "   - Klicke 'Submit' wenn du Änderungen machst!"
echo ""

echo "6. Test die OAuth URL direkt:"
echo "   Kopiere diese URL in deinen Browser:"
echo ""
echo "https://www.dropbox.com/oauth2/authorize?client_id=lkopmthbwccrgen&redirect_uri=https%3A%2F%2Fcautious-waddle-wj6rpvv76jw39x5q-3000.app.github.dev%2Fapi%2Foauth%2Fcallback%2Fdropbox&response_type=code&scope=files.content.write+files.content.read&state=%7B%22userId%22%3A%22test%22%2C%22integrationType%22%3A%22dropbox%22%7D&token_access_type=offline"
echo ""

echo "======================================"
echo "Wenn 'This app is not valid' erscheint:"
echo "======================================"
echo ""
echo "Mögliche Ursachen:"
echo ""
echo "1. App key stimmt nicht überein"
echo "   → Kopiere App key aus Dropbox Console"
echo "   → Trage in .env.local ein: NEXT_PUBLIC_DROPBOX_CLIENT_ID=<dein_key>"
echo ""
echo "2. Redirect URI nicht eingetragen"
echo "   → Gehe zu Settings → OAuth 2 → Redirect URIs"
echo "   → Klicke 'Add', füge URI ein, klicke 'Add', dann 'Submit'"
echo ""
echo "3. App ist 'Full Dropbox' statt 'Scoped access'"
echo "   → Erstelle neue App mit 'Scoped access'"
echo ""
echo "4. Permissions nicht aktiviert"
echo "   → Gehe zu Permissions Tab"
echo "   → Aktiviere files.content.write und files.content.read"
echo "   → Klicke 'Submit'"
echo ""

echo "======================================"
echo "Nächste Schritte:"
echo "======================================"
echo ""
echo "1. Prüfe ALLE Punkte oben in der Dropbox Console"
echo "2. Mache Screenshot von Settings Seite wenn es nicht funktioniert"
echo "3. Teste die URL aus Punkt 6 direkt im Browser"
echo "4. Wenn immer noch Fehler: Erstelle neue App mit 'Scoped access'"
echo ""
